# Generated by Django 5.2.1 on 2025-09-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('story', 'Story'), ('interview', 'Interview'), ('blog', 'Blog'), ('culture', 'Culture')], max_length=20, verbose_name='Тип статьи'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='submission_type',
            field=models.CharField(choices=[('recipe', 'Recipe'), ('story', 'Story')], max_length=20, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20, verbose_name='Сложность'),
        ),
    ]
